name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: make build
      - name: Test
        run: make test
